project_id = "oiljiebciwtjlrtqicty"

[functions]
  [functions.send-auth-email]
    verify_jwt = false
  [functions.send-invite-email]
    verify_jwt = false
  [functions.send-contact-email]
    verify_jwt = false
  [functions.upload-avatar]
    verify_jwt = false
  [functions.reset-password]
    verify_jwt = false
  [functions.confirm-email-change]
    verify_jwt = false
  [functions.check-annunci-scadenza]
    verify_jwt = false
  [functions.notify-annuncio-status]
    verify_jwt = false
  [functions.send-push-notification]
    verify_jwt = false
  [functions.import-fermate]
    verify_jwt = false
  [functions.import-gtfs]
    verify_jwt = false
