import { useState, useEffect, useMemo } from "react";

export interface Quartiere {
  nome: string;
  area: string;
}

// Lista completa dei micro-quartieri: Milano, Hinterland e Monza Brianza
const QUARTIERI: Quartiere[] = [
  // ── MILANO CENTRO (Municipio 1) ──
  { nome: "Duomo/Piazza della Scala", area: "Milano Centro" },
  { nome: "Brera/Moscova", area: "Milano Centro" },
  { nome: "Porta Nuova/Garibaldi", area: "Milano Centro" },
  { nome: "Porta Venezia/Corso Buenos Aires", area: "Milano Centro" },
  { nome: "Porta Romana/Crocetta", area: "Milano Centro" },
  { nome: "Porta Vittoria/Cinque Giornate", area: "Milano Centro" },
  { nome: "Porta Genova/Coni Zugna", area: "Milano Centro" },
  { nome: "Cadorna/Vincenzo Monti", area: "Milano Centro" },
  { nome: "Porta Volta/Arena", area: "Milano Centro" },
  { nome: "Magenta/Corso Magenta", area: "Milano Centro" },
  { nome: "San Babila/Montenapoleone", area: "Milano Centro" },
  { nome: "Missori/Corso Italia", area: "Milano Centro" },
  { nome: "Cairoli/Castello", area: "Milano Centro" },
  { nome: "Cordusio/Via Torino", area: "Milano Centro" },
  { nome: "Guastalla/Palazzo di Giustizia", area: "Milano Centro" },
  { nome: "Quadrilatero della Moda", area: "Milano Centro" },

  // ── MILANO NORD-OVEST (Municipio 8) ──
  { nome: "Fiera/City Life", area: "Milano Nord-Ovest" },
  { nome: "Sempione/Arco della Pace", area: "Milano Nord-Ovest" },
  { nome: "QT8/Monte Stella", area: "Milano Nord-Ovest" },
  { nome: "Gallaratese/San Leonardo", area: "Milano Nord-Ovest" },
  { nome: "Lampugnano/Olmi", area: "Milano Nord-Ovest" },
  { nome: "Quarto Oggiaro/Vialba", area: "Milano Nord-Ovest" },
  { nome: "Musocco/Certosa", area: "Milano Nord-Ovest" },
  { nome: "Villapizzone/Cagnola", area: "Milano Nord-Ovest" },
  { nome: "Trenno/Figino", area: "Milano Nord-Ovest" },
  { nome: "Portello/Pagano", area: "Milano Nord-Ovest" },
  { nome: "Bullona/Bramante", area: "Milano Nord-Ovest" },
  { nome: "Chinatown/Paolo Sarpi", area: "Milano Nord-Ovest" },
  { nome: "Ghisolfa/Mac Mahon", area: "Milano Nord-Ovest" },
  { nome: "Cenisio/Canonica", area: "Milano Nord-Ovest" },
  { nome: "Domodossola/De Angeli", area: "Milano Nord-Ovest" },

  // ── MILANO NORD (Municipio 9) ──
  { nome: "Isola/Porta Nuova", area: "Milano Nord" },
  { nome: "Niguarda/Ca' Granda", area: "Milano Nord" },
  { nome: "Bicocca/Arcimboldi", area: "Milano Nord" },
  { nome: "Affori/Bovisa", area: "Milano Nord" },
  { nome: "Dergano/Maciachini", area: "Milano Nord" },
  { nome: "Comasina/Bruzzano", area: "Milano Nord" },
  { nome: "Fulvio Testi/Segnano", area: "Milano Nord" },
  { nome: "Bovisasca/Quarto Cagnino", area: "Milano Nord" },
  { nome: "Prato Centenaro/Parco Nord", area: "Milano Nord" },
  { nome: "Stazione Garibaldi/Gioia", area: "Milano Nord" },

  // ── MILANO NORD-EST (Municipio 2) ──
  { nome: "Stazione Centrale/Repubblica", area: "Milano Nord-Est" },
  { nome: "NoLo/Via Padova", area: "Milano Nord-Est" },
  { nome: "Greco/Segnano", area: "Milano Nord-Est" },
  { nome: "Precotto/Adriano", area: "Milano Nord-Est" },
  { nome: "Crescenzago/Cimiano", area: "Milano Nord-Est" },
  { nome: "Gorla/Turro", area: "Milano Nord-Est" },
  { nome: "Maggiolina/Istria", area: "Milano Nord-Est" },
  { nome: "Loreto/Casoretto", area: "Milano Nord-Est" },
  { nome: "Piola/Pasteur", area: "Milano Nord-Est" },
  { nome: "Cascina dei Prati/Ponte Nuovo", area: "Milano Nord-Est" },
  { nome: "Villa San Giovanni/Udine", area: "Milano Nord-Est" },

  // ── MILANO EST (Municipio 3) ──
  { nome: "Città Studi/Politecnico", area: "Milano Est" },
  { nome: "Lambrate/Ortica", area: "Milano Est" },
  { nome: "Piazza Ascoli/Via Juvara", area: "Milano Est" },
  { nome: "Rubattino/Mecenate", area: "Milano Est" },
  { nome: "Feltre/Cascina Gobba", area: "Milano Est" },
  { nome: "Parco Lambro/Cimiano", area: "Milano Est" },
  { nome: "Argonne/Corsica", area: "Milano Est" },

  // ── MILANO SUD-EST (Municipio 4) ──
  { nome: "Corvetto/Porto di Mare", area: "Milano Sud-Est" },
  { nome: "Rogoredo/Santa Giulia", area: "Milano Sud-Est" },
  { nome: "Taliedo/Morsenchio", area: "Milano Sud-Est" },
  { nome: "Forlanini/Linate", area: "Milano Sud-Est" },
  { nome: "Monlué/Ponte Lambro", area: "Milano Sud-Est" },
  { nome: "Calvairate/Molise", area: "Milano Sud-Est" },
  { nome: "Lodi/Brenta", area: "Milano Sud-Est" },

  // ── MILANO SUD (Municipio 5) ──
  { nome: "Navigli/Darsena", area: "Milano Sud" },
  { nome: "Vigentino/Fatima", area: "Milano Sud" },
  { nome: "Chiaravalle/Nosedo", area: "Milano Sud" },
  { nome: "Gratosoglio/Missaglia", area: "Milano Sud" },
  { nome: "Chiesa Rossa/Conchetta", area: "Milano Sud" },
  { nome: "Stadera/Meda", area: "Milano Sud" },
  { nome: "Tibaldi/Bocconi", area: "Milano Sud" },
  { nome: "Ripamonti/Quintosole", area: "Milano Sud" },

  // ── MILANO SUD-OVEST (Municipio 6) ──
  { nome: "Barona/Santa Rita", area: "Milano Sud-Ovest" },
  { nome: "Giambellino/Lorenteggio", area: "Milano Sud-Ovest" },
  { nome: "Solari/Tortona", area: "Milano Sud-Ovest" },
  { nome: "Ronchetto sul Naviglio/Baggio", area: "Milano Sud-Ovest" },
  { nome: "Famagosta/Cantalupa", area: "Milano Sud-Ovest" },
  { nome: "Ludovico il Moro/Alzaia Naviglio", area: "Milano Sud-Ovest" },
  { nome: "San Cristoforo/Barona", area: "Milano Sud-Ovest" },

  // ── MILANO OVEST (Municipio 7) ──
  { nome: "San Siro/Ippodromo", area: "Milano Ovest" },
  { nome: "Baggio/Olmi", area: "Milano Ovest" },
  { nome: "Figino/Parco delle Cave", area: "Milano Ovest" },
  { nome: "Washington/Piazza Napoli", area: "Milano Ovest" },
  { nome: "Muggiano/Quinto Romano", area: "Milano Ovest" },
  { nome: "Selinunte/Rembrandt", area: "Milano Ovest" },
  { nome: "Forze Armate/Inganni", area: "Milano Ovest" },
  { nome: "De Angeli/Wagner", area: "Milano Ovest" },
  { nome: "Gambara/Bande Nere", area: "Milano Ovest" },

  // ── HINTERLAND NORD ──
  { nome: "Sesto San Giovanni/Centro", area: "Hinterland Nord" },
  { nome: "Sesto Rondò", area: "Hinterland Nord" },
  { nome: "Sesto/Cascina de' Gatti", area: "Hinterland Nord" },
  { nome: "Sesto/Restellone", area: "Hinterland Nord" },
  { nome: "Cinisello Balsamo/Centro", area: "Hinterland Nord" },
  { nome: "Cinisello/Balsamo Parco Nord", area: "Hinterland Nord" },
  { nome: "Cinisello/Sant'Eusebio", area: "Hinterland Nord" },
  { nome: "Bresso/Centro", area: "Hinterland Nord" },
  { nome: "Bresso/Parco Nord", area: "Hinterland Nord" },
  { nome: "Cusano Milanino/Centro", area: "Hinterland Nord" },
  { nome: "Cologno Monzese/Centro", area: "Hinterland Nord" },
  { nome: "Cologno Monzese/San Maurizio", area: "Hinterland Nord" },
  { nome: "Vimodrone/Centro", area: "Hinterland Nord" },
  { nome: "Cormano/Centro", area: "Hinterland Nord" },
  { nome: "Cormano/Ospiate", area: "Hinterland Nord" },
  { nome: "Paderno Dugnano/Centro", area: "Hinterland Nord" },
  { nome: "Paderno Dugnano/Dugnano", area: "Hinterland Nord" },
  { nome: "Paderno Dugnano/Palazzolo", area: "Hinterland Nord" },
  { nome: "Novate Milanese/Centro", area: "Hinterland Nord" },
  { nome: "Bollate/Centro", area: "Hinterland Nord" },
  { nome: "Bollate/Castellazzo", area: "Hinterland Nord" },
  { nome: "Bollate/Ospiate", area: "Hinterland Nord" },
  { nome: "Baranzate/Centro", area: "Hinterland Nord" },
  { nome: "Senago/Centro", area: "Hinterland Nord" },
  { nome: "Limbiate/Centro", area: "Hinterland Nord" },

  // ── HINTERLAND NORD-EST ──
  { nome: "Pioltello/Centro", area: "Hinterland Nord-Est" },
  { nome: "Pioltello/Seggiano", area: "Hinterland Nord-Est" },
  { nome: "Segrate/Centro", area: "Hinterland Nord-Est" },
  { nome: "Segrate/Milano 2", area: "Hinterland Nord-Est" },
  { nome: "Segrate/Villaggio Ambrosiano", area: "Hinterland Nord-Est" },
  { nome: "Rodano/Centro", area: "Hinterland Nord-Est" },
  { nome: "Peschiera Borromeo/Centro", area: "Hinterland Nord-Est" },
  { nome: "Pantigliate/Centro", area: "Hinterland Nord-Est" },
  { nome: "Gorgonzola/Centro", area: "Hinterland Nord-Est" },
  { nome: "Cassina de' Pecchi/Centro", area: "Hinterland Nord-Est" },
  { nome: "Brugherio/Centro", area: "Hinterland Nord-Est" },
  { nome: "Brugherio/San Damiano", area: "Hinterland Nord-Est" },
  { nome: "Carugate/Centro", area: "Hinterland Nord-Est" },
  { nome: "Agrate Brianza/Centro", area: "Hinterland Nord-Est" },
  { nome: "Vimercate/Centro", area: "Hinterland Nord-Est" },

  // ── HINTERLAND EST ──
  { nome: "San Donato Milanese/Centro", area: "Hinterland Est" },
  { nome: "San Donato/Metanopoli", area: "Hinterland Est" },
  { nome: "San Giuliano Milanese/Centro", area: "Hinterland Est" },
  { nome: "San Giuliano/Sesto Ulteriano", area: "Hinterland Est" },
  { nome: "Melegnano/Centro", area: "Hinterland Est" },
  { nome: "Mediglia/Centro", area: "Hinterland Est" },
  { nome: "Paullo/Centro", area: "Hinterland Est" },
  { nome: "Tribiano/Centro", area: "Hinterland Est" },

  // ── HINTERLAND SUD ──
  { nome: "Opera/Centro", area: "Hinterland Sud" },
  { nome: "Rozzano/Centro", area: "Hinterland Sud" },
  { nome: "Rozzano/Quinto de' Stampi", area: "Hinterland Sud" },
  { nome: "Rozzano/Ponte Sesto", area: "Hinterland Sud" },
  { nome: "Basiglio/Milano 3", area: "Hinterland Sud" },
  { nome: "Pieve Emanuele/Centro", area: "Hinterland Sud" },
  { nome: "Locate di Triulzi/Centro", area: "Hinterland Sud" },
  { nome: "Assago/Centro", area: "Hinterland Sud" },
  { nome: "Assago/Milanofiori", area: "Hinterland Sud" },
  { nome: "Buccinasco/Centro", area: "Hinterland Sud" },
  { nome: "Corsico/Centro", area: "Hinterland Sud" },
  { nome: "Corsico/Naviglio", area: "Hinterland Sud" },
  { nome: "Lacchiarella/Centro", area: "Hinterland Sud" },

  // ── HINTERLAND OVEST ──
  { nome: "Settimo Milanese/Centro", area: "Hinterland Ovest" },
  { nome: "Settimo/Seguro", area: "Hinterland Ovest" },
  { nome: "Trezzano sul Naviglio/Centro", area: "Hinterland Ovest" },
  { nome: "Cesano Boscone/Centro", area: "Hinterland Ovest" },
  { nome: "Cusago/Centro", area: "Hinterland Ovest" },
  { nome: "Pero/Centro", area: "Hinterland Ovest" },
  { nome: "Pero/Cerchiate", area: "Hinterland Ovest" },
  { nome: "Rho/Centro", area: "Hinterland Ovest" },
  { nome: "Rho/Fiera Milano", area: "Hinterland Ovest" },
  { nome: "Rho/Passirana", area: "Hinterland Ovest" },
  { nome: "Rho/Lucernate", area: "Hinterland Ovest" },
  { nome: "Cornaredo/Centro", area: "Hinterland Ovest" },
  { nome: "Cornaredo/San Pietro all'Olmo", area: "Hinterland Ovest" },
  { nome: "Bareggio/Centro", area: "Hinterland Ovest" },
  { nome: "Arluno/Centro", area: "Hinterland Ovest" },
  { nome: "Vittuone/Centro", area: "Hinterland Ovest" },
  { nome: "Pregnana Milanese/Centro", area: "Hinterland Ovest" },
  { nome: "Vanzago/Centro", area: "Hinterland Ovest" },
  { nome: "Pogliano Milanese/Centro", area: "Hinterland Ovest" },
  { nome: "Lainate/Centro", area: "Hinterland Ovest" },
  { nome: "Arese/Centro", area: "Hinterland Ovest" },
  { nome: "Garbagnate Milanese/Centro", area: "Hinterland Ovest" },

  // ── HINTERLAND NORD-OVEST ──
  { nome: "Legnano/Centro", area: "Hinterland Nord-Ovest" },
  { nome: "Legnano/Flora", area: "Hinterland Nord-Ovest" },
  { nome: "Parabiago/Centro", area: "Hinterland Nord-Ovest" },
  { nome: "Canegrate/Centro", area: "Hinterland Nord-Ovest" },
  { nome: "San Giorgio su Legnano/Centro", area: "Hinterland Nord-Ovest" },
  { nome: "Nerviano/Centro", area: "Hinterland Nord-Ovest" },
  { nome: "Rescaldina/Centro", area: "Hinterland Nord-Ovest" },
  { nome: "Cerro Maggiore/Centro", area: "Hinterland Nord-Ovest" },
  { nome: "Saronno/Centro", area: "Hinterland Nord-Ovest" },
  { nome: "Solaro/Centro", area: "Hinterland Nord-Ovest" },
  { nome: "Caronno Pertusella/Centro", area: "Hinterland Nord-Ovest" },

  // ── MONZA E BRIANZA ──
  { nome: "Monza/Centro Storico", area: "Monza e Brianza" },
  { nome: "Monza/Parco", area: "Monza e Brianza" },
  { nome: "Monza/San Rocco", area: "Monza e Brianza" },
  { nome: "Monza/San Biagio", area: "Monza e Brianza" },
  { nome: "Monza/Cederna", area: "Monza e Brianza" },
  { nome: "Monza/San Carlo", area: "Monza e Brianza" },
  { nome: "Monza/San Donato", area: "Monza e Brianza" },
  { nome: "Monza/Triante", area: "Monza e Brianza" },
  { nome: "Monza/San Giuseppe", area: "Monza e Brianza" },
  { nome: "Monza/Libertà", area: "Monza e Brianza" },
  { nome: "Monza/Regina Pacis", area: "Monza e Brianza" },
  { nome: "Monza/San Fruttuoso", area: "Monza e Brianza" },
  { nome: "Monza/Cazzaniga", area: "Monza e Brianza" },
  { nome: "Lissone/Centro", area: "Monza e Brianza" },
  { nome: "Lissone/Santa Margherita", area: "Monza e Brianza" },
  { nome: "Desio/Centro", area: "Monza e Brianza" },
  { nome: "Desio/San Giorgio", area: "Monza e Brianza" },
  { nome: "Seregno/Centro", area: "Monza e Brianza" },
  { nome: "Seregno/San Salvatore", area: "Monza e Brianza" },
  { nome: "Cesano Maderno/Centro", area: "Monza e Brianza" },
  { nome: "Cesano Maderno/Binzago", area: "Monza e Brianza" },
  { nome: "Muggiò/Centro", area: "Monza e Brianza" },
  { nome: "Nova Milanese/Centro", area: "Monza e Brianza" },
  { nome: "Giussano/Centro", area: "Monza e Brianza" },
  { nome: "Meda/Centro", area: "Monza e Brianza" },
  { nome: "Seveso/Centro", area: "Monza e Brianza" },
  { nome: "Bovisio-Masciago/Centro", area: "Monza e Brianza" },
  { nome: "Varedo/Centro", area: "Monza e Brianza" },
  { nome: "Villasanta/Centro", area: "Monza e Brianza" },
  { nome: "Arcore/Centro", area: "Monza e Brianza" },
  { nome: "Concorezzo/Centro", area: "Monza e Brianza" },
  { nome: "Vedano al Lambro/Centro", area: "Monza e Brianza" },
  { nome: "Biassono/Centro", area: "Monza e Brianza" },
  { nome: "Macherio/Centro", area: "Monza e Brianza" },
  { nome: "Sovico/Centro", area: "Monza e Brianza" },
  { nome: "Albiate/Centro", area: "Monza e Brianza" },
  { nome: "Carate Brianza/Centro", area: "Monza e Brianza" },
  { nome: "Besana in Brianza/Centro", area: "Monza e Brianza" },
  { nome: "Triuggio/Centro", area: "Monza e Brianza" },
  { nome: "Veduggio con Colzano/Centro", area: "Monza e Brianza" },
  { nome: "Renate/Centro", area: "Monza e Brianza" },
  { nome: "Bernareggio/Centro", area: "Monza e Brianza" },
  { nome: "Carnate/Centro", area: "Monza e Brianza" },
  { nome: "Usmate Velate/Centro", area: "Monza e Brianza" },
  { nome: "Ornago/Centro", area: "Monza e Brianza" },
  { nome: "Burago di Molgora/Centro", area: "Monza e Brianza" },
  { nome: "Sulbiate/Centro", area: "Monza e Brianza" },
];

// Raggruppa per area
const AREE = [...new Set(QUARTIERI.map(q => q.area))];

export const useQuartieri = () => {
  const quartieri = useMemo(() => QUARTIERI, []);
  const aree = useMemo(() => AREE, []);

  return { quartieri, aree };
};

export { QUARTIERI, AREE };
